local function animate_ground(self)
	local pos = go.get_position("ground")
	go.animate("ground", "position.x", go.PLAYBACK_LOOP_FORWARD, pos.x - 456, go.EASING_LINEAR, 456 / (self.speed * 60))
end

function init(self)
	self.speed = 6
	animate_ground(self)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("set_speed") then
		self.speed = message.speed
		animate_ground(self)
	end
end
