go.property("speed", 30)

function init(self)
	local pos = go.get_position(".")
	local endx = 1280
	go.animate(".", "position.x", go.PLAYBACK_ONCE_FORWARD, -endx, go.EASING_LINEAR, (endx + pos.x) / self.speed, 0,
		function(self)
			local pos = go.get_position(".")
			pos.x = endx
			go.set_position(pos, ".")
			go.animate(".", "position.x", go.PLAYBACK_LOOP_FORWARD, -endx, go.EASING_LINEAR, (endx + pos.x) / self.speed)
		end)
end
